namespace Volk.Core
{
    public enum OperatorType
    {
        Assignment,
        LogicalOr,
        LogicalAnd,
        BitwiseOr,
        BitwiseAnd,
        Eq,
        Ne,
        Gt,
        Ge,
        Lt,
        Le,
        Add,
        Sub,
        Mul,
        Div,
        Mod,
        Neg,
        ShiftLeft,
        ShiftRight,
        UnaryIncrement,
        UnaryDecrement,
        Cast,
        Dot,
    }
}